# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('username', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Judge_Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Registrar',
            fields=[
                ('username', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Score_Criterion',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('entry_name', models.CharField(max_length=128)),
                ('registrar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heartland.Registrar')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('judge_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='heartland.Judge')),
            ],
            options={
                'abstract': False,
            },
            bases=('heartland.judge',),
        ),
        migrations.AddField(
            model_name='score',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heartland.Score_Criterion'),
        ),
        migrations.AddField(
            model_name='score',
            name='scores',
            field=models.ManyToManyField(to='heartland.Judge_Team'),
        ),
        migrations.AddField(
            model_name='judge_team',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heartland.Judge'),
        ),
        migrations.AddField(
            model_name='judge_team',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heartland.Team'),
        ),
        migrations.AddField(
            model_name='category',
            name='criteria',
            field=models.ManyToManyField(to='heartland.Score_Criterion'),
        ),
        migrations.AlterUniqueTogether(
            name='judge_team',
            unique_together=set([('judge', 'team')]),
        ),
    ]
