# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 04:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Judge_Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Judge')),
            ],
        ),
        migrations.CreateModel(
            name='Registrar',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Score_Criterion',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('entry_name', models.CharField(max_length=128)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category')),
                ('registrar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Registrar')),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Score_Criterion'),
        ),
        migrations.AddField(
            model_name='score',
            name='judge_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Judge_Team'),
        ),
        migrations.AddField(
            model_name='judge_team',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Team'),
        ),
        migrations.AddField(
            model_name='category',
            name='criteria',
            field=models.ManyToManyField(to='core.Score_Criterion'),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set([('judge_team', 'criterion')]),
        ),
        migrations.AlterUniqueTogether(
            name='judge_team',
            unique_together=set([('judge', 'team')]),
        ),
    ]
