# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('username', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Registrar',
            fields=[
                ('username', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Score_Criterion',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('entry_name', models.CharField(max_length=128)),
                ('registrar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Registrar')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('judge_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Judge')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.judge',),
        ),
        migrations.CreateModel(
            name='Judge_Team',
            fields=[
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.Judge')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Team')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='criteria',
            field=models.ManyToManyField(to='core.Score_Criterion'),
        ),
        migrations.AddField(
            model_name='score_criterion',
            name='scores',
            field=models.ManyToManyField(to='core.Judge_Team'),
        ),
    ]
